### PR TITLE
Fixed warnings + added a new macro

### PR DESCRIPTION
**Pull request by BullyWiiPlaza**
Hello,

thanks for your useful header.

I fixed compile warnings, including:
* `constexpr can be used`
* `hides previous local declaration` due to `_ui_scope_guard` being multiply defined in the same scope when using more than 1 of your macros

I also added a new macro `with_Frame` which might be useful to start a new ImGui frame. It supports injecting a platform specific rendering setup with the `begin_frame` function.

I just wanted to contribute something back in case you care, if not, that's fine, too.

### CODE REVIEW

**Comment by mnesarco** [comment]
Thank you for your contribution. I will review it, but at a first bird eye there are a couple of things that are not subject to change here in the upstream version:
- file names (`imgui_sugar.hpp`)
- imgui subfolder inclusion (`imgui/imgui.h`)
- coding style (code format)
- a dependency on std will not be added (`<functional>`)

Other notes:
- The `constexpr if` check is nice,  good catch.
- hiding names in deeper scopes is not an error but I can see that a warning could be annoying. I will check the issue and your solution (`IMGUI_SUGAR_UNIQUE_NAME`)

Once again, thank you for contributing back your ideas.

**Comment by mnesarco** [comment]
The `constexpr if` is a **c++17** feature. As the minimum supported version of imgui is **c++14**, this cannot be added yet.

**Comment by BullyWiiPlaza** [comment]
> The `constexpr if` is a **c++17** feature. As the minimum supported version of imgui is **c++14**, this cannot be added yet.

I see. If someone is using the latest C++ standard in Visual Studio, this code generates a warning. Maybe it would be better to suppress it via some pragma then to keep it C++14 compatible.

**Comment by mnesarco** [comment]
Hi @BullyWiiPlaza , thank you for your contribution. I have fixed the issue with a different trick. Now it is effectively doing the same thing as `if constexpr (...) { ... }` but without using it, so no hard requirement to require c++17.

**Comment by mnesarco** [comment]
`IMGUI_SUGAR_UNIQUE_NAME` is good. If you what to send a PR with only that change, I will merge then. Or if you prefer I can do the change directly.

**Comment by BullyWiiPlaza** [comment]
> `IMGUI_SUGAR_UNIQUE_NAME` is good. If you what to send a PR with only that change, I will merge then. Or if you prefer I can do the change directly.

You can go ahead and commit all changes you like by yourself, that's fine.

**Comment by mnesarco** [comment]
Summary:

Accepted and Included changes:
1. Fix include to `<imgui.h>`
2. manage `if constexpr` (without c++17)
3. `IMGUI_SUGAR_UNIQUE_NAME`

Not included:
1. File name changes
2. Coding style changes
3. requirement of c++17
4. std dependency

**Pull request closed without merging**
